# This workflow will do a clean install of node dependencies, build the source code and run tests across different
# versions of node.
# See: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node_version: [16.x]
        os: [windows-latest] # or [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm ci
      - run: npm run build
        env:
          # ToDo: remove this.
          #   Temporarily added because the build has 2 warnings (and warnings are normally treated as errors).
          #   Both warnings say: React Hook React.useEffect has a missing dependency: 'analytics'.
          CI: ''
      - run: npm test
      - run: npm run integration
